"""initial schema

Revision ID: 001
Revises:
Create Date: 2024-01-01 10:00:00

Task 1 — Step 95: First autogenerated migration.
Creates all 5 tables: departments, students, courses, enrollments, professors.
"""

from alembic import op
import sqlalchemy as sa

# ─── Revision identifiers ─────────────────────────────────────────────────────
revision  = '001'
down_revision = None          # None = this is the very first migration
branch_labels = None
depends_on    = None


# ─── upgrade() ───────────────────────────────────────────────────────────────
# Applied when you run:  alembic upgrade head
def upgrade() -> None:

    # 1. departments (created first — no foreign key dependencies)
    op.create_table(
        'departments',
        sa.Column('department_id', sa.Integer(),     primary_key=True, autoincrement=True),
        sa.Column('dept_name',     sa.String(100),   nullable=False),
        sa.Column('head_of_dept',  sa.String(100),   nullable=True),
        sa.Column('budget',        sa.Numeric(12, 2), nullable=True),
    )

    # 2. students
    op.create_table(
        'students',
        sa.Column('student_id',      sa.Integer(),    primary_key=True, autoincrement=True),
        sa.Column('first_name',      sa.String(50),   nullable=False),
        sa.Column('last_name',       sa.String(50),   nullable=False),
        sa.Column('email',           sa.String(100),  nullable=False, unique=True),
        sa.Column('date_of_birth',   sa.Date(),       nullable=True),
        sa.Column('department_id',   sa.Integer(),    nullable=True),
        sa.Column('enrollment_year', sa.Integer(),    nullable=True),
        sa.ForeignKeyConstraint(['department_id'], ['departments.department_id']),
    )

    # 3. courses
    op.create_table(
        'courses',
        sa.Column('course_id',     sa.Integer(),    primary_key=True, autoincrement=True),
        sa.Column('course_name',   sa.String(150),  nullable=False),
        sa.Column('course_code',   sa.String(20),   nullable=True, unique=True),
        sa.Column('credits',       sa.Integer(),    nullable=True),
        sa.Column('department_id', sa.Integer(),    nullable=True),
        sa.Column('max_seats',     sa.Integer(),    nullable=True, server_default='60'),
        sa.ForeignKeyConstraint(['department_id'], ['departments.department_id']),
    )

    # 4. enrollments
    op.create_table(
        'enrollments',
        sa.Column('enrollment_id',   sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('student_id',      sa.Integer(), nullable=True),
        sa.Column('course_id',       sa.Integer(), nullable=True),
        sa.Column('enrollment_date', sa.Date(),    nullable=True),
        sa.Column('grade',           sa.CHAR(2),   nullable=True),
        sa.ForeignKeyConstraint(['student_id'], ['students.student_id']),
        sa.ForeignKeyConstraint(['course_id'],  ['courses.course_id']),
    )

    # 5. professors
    op.create_table(
        'professors',
        sa.Column('professor_id',  sa.Integer(),     primary_key=True, autoincrement=True),
        sa.Column('prof_name',     sa.String(100),   nullable=False),
        sa.Column('email',         sa.String(100),   nullable=True, unique=True),
        sa.Column('department_id', sa.Integer(),     nullable=True),
        sa.Column('salary',        sa.Numeric(10,2), nullable=True),
        sa.ForeignKeyConstraint(['department_id'], ['departments.department_id']),
    )


# ─── downgrade() ─────────────────────────────────────────────────────────────
# Applied when you run:  alembic downgrade base
def downgrade() -> None:
    # Drop in reverse order to respect foreign key constraints
    op.drop_table('professors')
    op.drop_table('enrollments')
    op.drop_table('courses')
    op.drop_table('students')
    op.drop_table('departments')
